from tkinter import *
from tkinter import ttk

import Variables
import ThirdWindow

def openSecondWindow():
    Variables.secondWindowFlag = 1

    secW = Toplevel()
    secW.title("Elden Ring Optimizer")
    secW.grid()

    ttk.Label(secW, text="Zaznacz jakie lokacje są dostępne?").grid(column=1, row=0)
    roundH = IntVar()
    rhCB = ttk.Checkbutton(secW, text="Twierdza okrągłego stołu", onvalue=True, offvalue=False, variable=roundH)
    rhCB.grid(column=0, row=1)
    limgrave = IntVar()
    limCB = ttk.Checkbutton(secW, text="Pogrobno", onvalue=True, offvalue=False, variable=limgrave)
    limCB.grid(column=1, row=1)
    peninsula = IntVar()
    wpCB = ttk.Checkbutton(secW, text="Płaczący Półwysep", onvalue=True, offvalue=False, variable=peninsula)
    wpCB.grid(column=2, row=1)
    caelid = IntVar()
    caelCB = ttk.Checkbutton(secW, text="Caelid", onvalue=True, offvalue=False, variable=caelid)
    caelCB.grid(column=0, row=2)
    liurnia = IntVar()
    liurniaCB = ttk.Checkbutton(secW, text="Jeziorna Liurnia", onvalue=True, offvalue=False, variable=liurnia)
    liurniaCB.grid(column=1, row=2)
    altus = IntVar()
    altusCB = ttk.Checkbutton(secW, text="Płaskowyż Altus", onvalue=True, offvalue=False, variable=altus)
    altusCB.grid(column=2, row=2)
    leyndell_royal = IntVar()
    lrcCB = ttk.Checkbutton(secW, text="Leyndell, Królewska Stolica", onvalue=True, offvalue=False,
                            variable=leyndell_royal)
    lrcCB.grid(column=0, row=3)
    giants = IntVar()
    giantsCB = ttk.Checkbutton(secW, text="Szczyt Olbrzymów", onvalue=True, offvalue=False, variable=giants)
    giantsCB.grid(column=1, row=3)
    farum = IntVar()
    farumCB = ttk.Checkbutton(secW, text="Przeklęte Farum Azula", onvalue=True, offvalue=False, variable=farum)
    farumCB.grid(column=2, row=3)
    leyndell_ashen = IntVar()
    lacCB = ttk.Checkbutton(secW, text="Leyndell, Stolica Popiołów", onvalue=True, offvalue=False,
                            variable=leyndell_ashen)
    lacCB.grid(column=0, row=4)
    snowfield = IntVar()
    csCB = ttk.Checkbutton(secW, text="Uświęcona Śnieżna Równina", onvalue=True, offvalue=False, variable=snowfield)
    csCB.grid(column=1, row=4)
    haligtree = IntVar()
    haligCB = ttk.Checkbutton(secW, text="Święte Drzewo Miquella'i", onvalue=True, offvalue=False, variable=haligtree)
    haligCB.grid(column=2, row=4)
    nokron = IntVar()
    nokronCB = ttk.Checkbutton(secW, text="Nokron, Wieczne Miasto", onvalue=True, offvalue=False, variable=nokron)
    nokronCB.grid(column=0, row=5)
    nokstella = IntVar()
    noksCB = ttk.Checkbutton(secW, text="Nokstela, Wieczne Miasto", onvalue=True, offvalue=False, variable=nokstella)
    noksCB.grid(column=1, row=5)
    ainsel = IntVar()
    ainselCB = ttk.Checkbutton(secW, text="Rzeka Ainsel", onvalue=True, offvalue=False, variable=ainsel)
    ainselCB.grid(column=2, row=5)
    siofra = IntVar()
    siofraCB = ttk.Checkbutton(secW, text="Rzeka Siofra", onvalue=True, offvalue=False, variable=siofra)
    siofraCB.grid(column=0, row=6)
    lake = IntVar()
    lrCB = ttk.Checkbutton(secW, text="Jezioro Zgnilizny", onvalue=True, offvalue=False, variable=lake)
    lrCB.grid(column=1, row=6)
    mauzoleum = IntVar()
    mauzoleumCB = ttk.Checkbutton(secW, text="Mauzoleum Dynastii Mohgwyn'a", onvalue=True, offvalue=False,
                                  variable=mauzoleum)
    mauzoleumCB.grid(column=2, row=6)
    forsaken = IntVar()
    cfCB = ttk.Checkbutton(secW, text="Katedra Zapomnianych", onvalue=True, offvalue=False, variable=forsaken)
    cfCB.grid(column=0, row=7)
    underground = IntVar()
    suCB = ttk.Checkbutton(secW, text="Podziemne Poboczne Drogi", onvalue=True, offvalue=False, variable=underground)
    suCB.grid(column=1, row=7)
    deep = IntVar()
    deepCB = ttk.Checkbutton(secW, text="Głębiny", onvalue=True, offvalue=False, variable=deep)
    deepCB.grid(column=2, row=7)

    ttk.Label(secW, text="Zaznacz przeciwników, którzy zostali pokonani?").grid(column=1, row=8)
    rennala = IntVar()
    rennalaCB = ttk.Checkbutton(secW, text="Rennala, Królowa Pełni Księżyca", onvalue=True, offvalue=False,
                                variable=rennala)
    rennalaCB.grid(column=0, row=9)
    morgott = IntVar()
    morgottCB = ttk.Checkbutton(secW, text="Morgott, Król Omenów", onvalue=True, offvalue=False, variable=morgott)
    morgottCB.grid(column=1, row=9)
    maliketh = IntVar()
    malikethCB = ttk.Checkbutton(secW, text="Maliketh, Czarna Klinga", onvalue=True, offvalue=False, variable=maliketh)
    malikethCB.grid(column=2, row=9)
    godfrey = IntVar()
    godfreyCB = ttk.Checkbutton(secW, text="Godfrey, Pierwszy Eldeński Władca", onvalue=True, offvalue=False,
                                variable=godfrey)
    godfreyCB.grid(column=0, row=10)
    radahn = IntVar()
    radahnCB = ttk.Checkbutton(secW, text="Radahn, Gwiezdna Plaga", onvalue=True, offvalue=False, variable=radahn)
    radahnCB.grid(column=1, row=10)
    elemer = IntVar()
    elemerCB = ttk.Checkbutton(secW, text="Elemer od Głogu", onvalue=True, offvalue=False, variable=elemer)
    elemerCB.grid(column=2, row=10)
    niall = IntVar()
    niallCB = ttk.Checkbutton(secW, text="Dowódca Niall", onvalue=True, offvalue=False, variable=niall)
    niallCB.grid(column=0, row=11)
    mohg = IntVar()
    mohgCB = ttk.Checkbutton(secW, text="Mohg, Pan Krwi", onvalue=True, offvalue=False, variable=mohg)
    mohgCB.grid(column=1, row=11)
    loretta = IntVar()
    lorettaCB = ttk.Checkbutton(secW, text="Loretta, Rycerz Świętego Drzewa", onvalue=True, offvalue=False,
                                variable=loretta)
    lorettaCB.grid(column=2, row=11)
    malenia = IntVar()
    maleniaCB = ttk.Checkbutton(secW, text="Malenia, Ostrze Miquella'i", onvalue=True, offvalue=False, variable=malenia)
    maleniaCB.grid(column=0, row=12)

    def setParameters():
        if Variables.thirdWindowFlag == 0:
            Variables.regions[0] = ainsel.get()
            Variables.regions[2] = altus.get()
            Variables.regions[4] = caelid.get()
            Variables.regions[6] = forsaken.get()
            Variables.regions[8] = snowfield.get()
            Variables.regions[10] = farum.get()
            Variables.regions[12] = deep.get()
            Variables.regions[14] = lake.get()
            Variables.regions[16] = leyndell_ashen.get()
            Variables.regions[18] = leyndell_royal.get()
            Variables.regions[20] = limgrave.get()
            Variables.regions[22] = liurnia.get()
            Variables.regions[24] = haligtree.get()
            Variables.regions[26] = mauzoleum.get()
            Variables.regions[28] = giants.get()
            Variables.regions[30] = nokron.get()
            Variables.regions[32] = nokstella.get()
            Variables.regions[34] = roundH.get()
            Variables.regions[36] = siofra.get()
            Variables.regions[38] = underground.get()
            Variables.regions[40] = peninsula.get()

            Variables.bosses[0] = niall.get()
            Variables.bosses[2] = elemer.get()
            Variables.bosses[4] = godfrey.get()
            Variables.bosses[6] = loretta.get()
            Variables.bosses[8] = malenia.get()
            Variables.bosses[10] = maliketh.get()
            Variables.bosses[12] = mohg.get()
            Variables.bosses[14] = morgott.get()
            Variables.bosses[16] = rennala.get()
            Variables.bosses[18] = radahn.get()

            ThirdWindow.openThirdWindow()
        return 0

    def closeWindow():
        if Variables.thirdWindowFlag == 0:
            Variables.secondWindowFlag = 0
            secW.withdraw()
        return 0

    ttk.Button(secW, text="Powrót", command=closeWindow).grid(column=0, row=13)
    ttk.Button(secW, text="Dalej", command=setParameters).grid(column=2, row=13)

    secW.mainloop()
